### ISSUE TITLE
Custom boxes for TF Siren group

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Tanoa-Takedown#10]
Stuck on box creation. I hate it but want to get it done. Can someone jump in here and lend a brother a hand? I have the first box created but want to make them all work with JIP and work properly to help keep duplications to a minimum.

**Comment by coachwn** [comment]
Need to finish the boxes.

**Comment by coachwn** [comment]
Anyone able to help out here???

**Comment by FoxKilo** [comment]
Just saw the empty SQFs for the boxes, didn't realise they were empty. Medical is self explanatory but you'd need to PM me with what faction equipment should/shouldn't be in there.

**Comment by coachwn** [comment]
With the medical it just needs basically the same things we have in our primary medical boxes for every mission. As for the other stuff I have the class names on some of the others. I will be home in about 40 minutes from work and will have time to talk via TS then.

**Comment by coachwn** [comment]
Did not get finished with boxes last night. Version that is on server is still the version Fox uploaded yesterday. I will be home before noon my time today.

**Comment by Scotty-Z** [comment]
these got finished right?

**Comment by coachwn** [comment]
Sort of...I think I did something wrong because I can't get them to appear on the server when I aM testing them. It keeps tossing out errors when I try to spawn them in. Will put the file up here today when I get a chance to do it.

**Comment by Scotty-Z** [comment]
post them up ill take a look
