### ISSUE TITLE
V12 random 15th PLA occasional spawn, Marshall main gun bug and no extra crap in Prowlers

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Tanoa-Takedown#30]
Small bugs found in things.

1st is Spyder Addons creates problems with enemy in vehicles and it doesn't obey blacklisted areas...totally removed enemy from civ vehicles in the module...fixed.

2nd Marshall main gun only has 1 reload for 60 rounds and 1 reload for 40 rounds despite the fix by Jmaster with his weapon replacement script. Good news is I get no errors when loading the mission now with that script.

3rd is Prowlers and SF MRZR's have no extra junk in their inventory areas...as they should. I am checking that again to see if I entered it incorrectly but I am sure all I did was change the init in the vehicle per instructions to optimize the code. 

Where is the old way of doing that code for the sfuaz.sqf script from Queen's Stallions....it worked.

**Comment by Jmaster9999** [comment]
Marshal gun reload bug is due to using a different classname than the one used in the mission, updating the customvehicleweaponInit.sqf will fix the issue.
